name: Update RSS Feed

on:
  schedule:
    - cron: '*/20 * * * *'  # 每 20 分钟运行一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install feedparser

    - name: Run fetch_rss.py
      run: |
        python3 fetch_rss.py

    - name: Commit and push feed.xml
      uses: EndBug/add-and-commit@v9
      with:
        author_name: andersonball
        author_email: freeanderson2020@gmail.com
        message: 'Update RSS feed'
        add: 'feed.xml'
        push: 'origin main'
        token: ${{ secrets.ACTIONS_PAT }}  # 使用刚才创建的 PAT
